name: Django CI

on:
  push:
    branches: [ Feature/Docker ]
  pull_request:
    branches: [ Feature/Docker ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install docker-compose
    - name: Run Tests
      run: |
        docker-compose run app sh -c "python manage.py test && flake8"
